theme: jekyll-theme-cayman
title: Avoiding Side Effects in Complex Environments
subtitle: Alex Turner*, Neale Ratzlaff*, Prasad Tadepalli
description: Making RL agents behave with an unsupervised penalty term.
logo: /aup.png
repo_url: https://github.com/neale/safelife-k2
permalink: https://github.com/neale/safelife-k2
github:
  is_project_page: true
  repository_url: https://github.com/neale/safelife-k2
site:
  test: foo
  github:
    is_project_page: true
    repository_url: https://github.com/neale/safelife-k2
  publications:
    show_paper: true
    paper_url: https://arxiv.org/abs/2006.06547
  title: overwriting title
plugins:
  - 'jekyll-github-metadata'
